- build_ext.py
- poetry.lock
- pyproject.toml
- src/habluetooth/__init__.py
- src/habluetooth/advertisement_tracker.pxd
- src/habluetooth/advertisement_tracker.py
- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
- src/habluetooth/manager.pxd
- src/habluetooth/manager.py
- src/habluetooth/models.pxd
- src/habluetooth/models.py
- src/habluetooth/scanner.pxd
- src/habluetooth/scanner.py
- tests/__init__.py
- tests/test_models.py
~~TODO: We can't do _previous_service_info yet because HA restores _discovered_device_timestamps which we want to get rid of~~
~~We need a `.restore` function that takes a `DiscoveredDeviceAdvertisementData` and a `.serialize` function that returns a `DiscoveredDeviceAdvertisementData`~~
> feat: relocate BluetoothServiceInfoBleak

- src/habluetooth/__init__.py
- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
- src/habluetooth/central_manager.py
- src/habluetooth/manager.py
- src/habluetooth/scanner.pxd
- src/habluetooth/scanner.py
- src/habluetooth/scanner_device.py
- src/habluetooth/wrappers.py
- tests/test_init.py
The callback always feeds into the manager so there is no need to pass it every time we create a scanner
> feat!: eliminate the need to pass the new_info_callback

- src/habluetooth/manager.py
This can be obtained from the scanner itself.
All other args will be kwargs to avoid future breaking changes
> feat!: simplify async_register_scanner by removing connectable argument

- src/habluetooth/manager.pxd
- src/habluetooth/manager.py
We did not account for jitter in the advertising interval so it would switch too quickly.
We now account for up to 5s of jitter
> fix: switching scanners too quickly

- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
- src/habluetooth/manager.py
- src/habluetooth/scanner.py
- src/habluetooth/wrappers.py
- tests/test_init.py
only store BluetoothServiceInfoBleak as _discovered_device_advertisement_datas can be generated on demand and is now only used for diagnostics
> feat: improve remote scanner performance

- src/habluetooth/manager.py
Make a copy of the set in case it changes during iteration
> fix: ensure unavailable callbacks can be removed from fired callbacks

- src/habluetooth/scanner.py
bleak uses DBus BlueZ Interface org.bluez.AdvertisementMonitor1 that will return ble packet data always filtred by [data section flags](https://www.google.com/search?q=ble+datasection+flags&oq=ble+datasection+flags&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQLhhA0gEINDA1NGowajSoAgCwAgA&sourceid=chrome&ie=UTF-8#ip=1) 
```
BLE_SIG_ADV_FLAG_LE_LIMITED_DISC_MODE (0x01)
BLE_SIG_ADV_FLAG_LE_GENERAL_DISC_MODE (0x02)
BLE_SIG_ADV_FLAG_BR_EDR_NOT_SUPPORTED (0x04)
BLE_SIG_ADV_FLAG_LE_BR_EDR_CONTROLLER (0x08)
BLE_SIG_ADV_FLAG_LE_BR_EDR_HOST (0x10)
BLE_SIG_ADV_FLAGS_LE_ONLY_LIMITED_DISC_MODE (0x05)
BLE_SIG_ADV_FLAGS_LE_ONLY_GENERAL_DISC_MODE (0x06)
```
there seems to be no way to force it to return all packets like in active scan mode 
currenty we are filterining flags **06** …
> fix: android beacons in passive mode with flags 0x02

- src/habluetooth/scanner.py
- tests/test_scanner.py
This to fix a un-intended breaking change introduced in 2.5.0
> fix: ensure discovered_devices returns an empty list for offline scanners

- src/habluetooth/scanner.pxd
- src/habluetooth/scanner.py
- tests/test_scanner.py
- only log warning on successful fallback
- add current and requested mode to diagnostics
Still seems to work ok with 7 adapters
> feat: improve fallback to passive mode when active mode fails

- src/habluetooth/base_scanner.py
- src/habluetooth/manager.py
- src/habluetooth/models.pxd
- src/habluetooth/models.py
- src/habluetooth/scanner.py
- tests/test_models.py
This is ~14% speed up for remote scanners.
`tx_power` is now required for `BluetoothServiceInfoBleak` which is a breaking change for tests
> feat!: make generation of AdvertisementData lazy

- src/habluetooth/scanner.py
These are only used for debugging and they generate 10000s of callbacks per minute that flood the debug logs with useless data.  Passive mode generated ~100x more log messages than active mode.
> feat: override DeviceFound and DeviceLost for passive monitoring

- .github/workflows/ci.yml
We cannot build these yet because bleak has a pin to < 3.13
> fix: disable 3.13 wheels

- src/habluetooth/const.py
- src/habluetooth/manager.pxd
- src/habluetooth/manager.py
The switch threshold was previously 5 which meant switching happened too frequently and reduced update frequency for devices which need to get updates from the same scanner because it was flip-flopping
Note that this does not affect the connect rssi calculation as that always uses the best available path
> fix: increase rssi switch threshold for advertisements

- src/habluetooth/const.py
followup to #110
Even at 10 we still see it switch too often in high density environments
It make make sense not to even switch at all anymore since we have a timeout when the data we have is stale.
> fix: increase RSSI switch value to 16

- src/habluetooth/manager.py
- src/habluetooth/models.py
- tests/conftest.py
- tests/test_manager.py
These should always be fixed to 0 free, 0 slots
> feat: add support for connection allocations for non-connectable scanners

- src/habluetooth/manager.py
Not filtering FindMy adverts provides more reliable detection of Apple products when using the "Private BLE Device" core integration and custom integrations such as Bermuda and in future the FindMy integration, particularly for OpenHaystack-derived devices.
> feat: include findmy packets in wanted adverts

- src/habluetooth/manager.py
- tests/test_manager.py
Allocations would not return anything if the adapter had never made any connections
> fix: ensure allocations are available if the adapter never makes any connections

- src/habluetooth/models.py
This was moved to central_manager.py but never removed from models
> fix: remove unused CentralBluetoothManager in models

- src/habluetooth/wrappers.py
2025-02-21 17:15:39.419 DEBUG (MainThread) [habluetooth.wrappers] 10:76:36:14:93:76 (TP393 (9376)): Found 2 connection paths, preferred order: kitchenalexproxy (24:4C:AB:03:63:A0) (RSSI=-92) (failures=0), masterbathalexproxy (24:4C:AB:03:0B:6C) (RSSI=-92) (failures=0)
2025-02-21 17:15:39.419 DEBUG (MainThread) [habluetooth.wrappers] 10:76:36:14:93:76 - TP393 (9376) -> 24:4C:AB:03:63:A0: Connecting via kitchenalexproxy (24:4C:AB:03:63:A0) (last rssi: -92)
> feat: add debug logging for connection paths

- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
- src/habluetooth/manager.py
- src/habluetooth/models.pxd
- src/habluetooth/models.py
- tests/__init__.py
- tests/conftest.py
- tests/test_base_scanner.py
- tests/test_manager.py
- tests/test_wrappers.py
Most of the time was spent doing `PyObject_RichCompare` on the previous advertisement data when it was the same object. We can switch this to be an `is` check instead.
> feat: improve manager performance

- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
Most of the time was spent doing `PyObject_RichCompare` on the previous advertisement data when it was the same object. We can switch this to be an `is` check instead.
> feat: improve performance of base_scanner

- src/habluetooth/manager.py
We should check if the set is empty and do nothing if there are no callbacks since we can avoid building the `AdvertisementData` on demand
> feat: avoid building on demand AdvertisementData if there are no bleak callbacks

- tests/test_benchmark_base_scanner.py
Some of the benchmarks where benchmarking the bleak objects because they were not created outside the benchmarked code
> chore: cleanup benchmarks to avoid building data in benchmark code

- src/habluetooth/base_scanner.pxd
- src/habluetooth/base_scanner.py
skip details merge if the BLEDevice already exists.
We only need to merge details when we create the BLEDevice since details will never change.
Noticed while building https://github.com/Bluetooth-Devices/habluetooth/pull/219 that the data never changes
> feat: improve performance of _async_on_advertisement_internal

- src/habluetooth/wrappers.py
- tests/test_wrappers.py
Logging could raise because there was not sorter callable
> fix: ensure logging does not fail when there is only a single scanner

- pyproject.toml
Currently there is a segfault with 3.1
> fix: pin Cython to <3.1

- src/habluetooth/base_scanner.py
This was a bad merge conflict resolution, but it
did not cause any production issues
> fix: remove duplicate _connecting slot from BaseHaScanner

- src/habluetooth/scanner.py
- tests/test_scanner.py
When bleak put the backends behind the bleak scanner, all the backends now have to make a copy of discovered devices every time we connect. Since linux is already in the right forward we can bypass that and look at seen_devices directly. Since we already rely on scanner._backend this is no less safe than the other place we have to do it anyways.
> fix: solve performance regression while connecting in Linux

- poetry.lock
- pyproject.toml
- src/habluetooth/wrappers.py
This PR adds detection and warning messages when BLE connections are established directly through `BleakClient.connect()` instead of using `bleak-retry-connector`'s `establish_connection()` function. This helps guide users toward more reliable connection establishment patterns.
- **Added `_is_retry_client` flag tracking** in `HaBleakClientWrapper.__init__()` to detect if a client was created through `establish_connection`
- **Added warning message** in `connect()` method that triggers when connections are made without bleak-retry-connector
- Warning message includes a link to the bleak-retry-connector documentation for user guidance
- **Modified `establish_connection()`** to pass `_is_retry_client=True` when creating client instances
- **Added test** …
> feat: warn when connections are established without bleak-retry-connector

- src/habluetooth/advertisement_tracker.pxd
- src/habluetooth/advertisement_tracker.py
- src/habluetooth/base_scanner.py
- tests/test_advertisement_tracker.py
- tests/test_scanner.py
This PR fixes an issue where advertising interval calculations become incorrect when a Bluetooth scanner pauses to establish a connection. The scanner stops listening for advertisements during connection attempts, but the timing collection continued, resulting in incorrectly large interval measurements that don't represent the actual advertising interval of devices.
When a scanner pauses to establish a BLE connection:
1. The scanner stops listening for advertisements
2. Timing collection data remains in memory
3. When the scanner resumes after the connection attempt, the next advertisement creates an incorrect interval: `time_after_connection - time_before_connection`
4. This artificially inflated interval doesn't represent the device's actual advertising pattern
- Added …
> fix: incorrect advertising interval calculation when scanner pauses for connections

- src/habluetooth/channels/bluez.py
- tests/channels/test_bluez.py
On certain system (specifically Odroid M1 with kernel 6.12.43-haos), the Bluetooth management socket's `sendto()` system call returns 0 instead of the number of bytes sent, even though the data is successfully transmitted. This causes asyncio's transport layer to think the send failed and retry indefinitely, leading to high CPU usage.
- **Broken**: Odroid M1 with kernel 6.12.43-haos (aarch64)
- **Working**: Odroid N2+ with kernel 6.12.43-haos (aarch64)
- **Working**: x86_64 systems with kernel 6.12.44-haos
```bash
sendto(7, "\25\0\0\0\0\0", 6, 0, NULL, 0) = 0
WARNING:asyncio:send data_len:6 bytes:0
WARNING:asyncio:data after 6
sendto(6, "\25\0\0\0\0\0", 6, 0, NULL, 0) = 6
```
The kernel has an ABI inconsistency where the Bluetooth management socket (AF_BLUETOOTH, SOCK_RAW, BTPROTO_HCI) …
> fix: workaround kernel ABI inconsistency in Bluetooth mgmt socket send behavior
