src/habluetooth/wrappers.py
https://github.com/home-assistant/core/issues/107086
=> fix: handle subclassed str in the client wrapper

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, src/habluetooth/models.pxd, src/habluetooth/models.py, src/habluetooth/scanner.pxd, src/habluetooth/scanner.py
This is ~20% speed up to processing raw adv data
=> feat: add a fast cython init path for BluetoothServiceInfoBleak

src/habluetooth/models.py
Avoids the lambda in
https://github.com/python/cpython/blob/d83fcf8371f2f33c7797bc8f5423a8bca8c46e5c/Lib/collections/__init__.py#L441
=> feat: speed up creation of AdvertisementData NamedTuple

.github/workflows/ci.yml
=> feat: start building wheels for Python 3.13

src/habluetooth/manager.py
=> feat: refactor scanner_adv_received to reduce ref counting

src/habluetooth/base_scanner.pxd, src/habluetooth/manager.pxd
stale_seconds should have been a double
=> fix: precision loss when comparing advs from different sources

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py
=> feat: reduce remote scanner adv processing overhead

.pre-commit-config.yaml, src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, src/habluetooth/scanner.pxd, src/habluetooth/scanner.py, tests/test_base_scanner.py, tests/test_manager.py, tests/test_scanner.py
Eventually we will show this in the UI, however for now its just for diagnostics
=> feat: allow remote scanners to set current and requested mode

poetry.lock, pyproject.toml, src/habluetooth/scanner.py
If the client is already discovering because something got out of sync https://github.com/bluez/bluez/blob/65fbc47143a5b0e8b889d39b758fe0056e54bc59/src/adapter.c#L2510 try to force stop discovery
=> fix: try to force stop discovery if its stuck on

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, src/habluetooth/scanner.py
We should be a bit louder about detecting failure seen in https://github.com/esphome/esphome/pull/8297 and https://github.com/esphome/issues/issues/6701
=> feat: improve logging of scanner failures and time_since_last_detection

build_ext.py
compile with -g0 to reduce wheel size
=> feat: reduce wheel sizes

src/habluetooth/base_scanner.py, src/habluetooth/scanner.py
related issue https://github.com/home-assistant/core/issues/140138
=> fix: downgrade scanner gone quiet logger to debug

src/habluetooth/base_scanner.py, src/habluetooth/manager.py
We don't have a good benchmark for this, but it makes a bit a difference locally
=> feat: improve performance of local name checks

tests/test_base_scanner.py
- reduce size of test
- add a test for merging in new data
=> chore: improve manufacturer_data history merge tests

src/habluetooth/models.pxd, src/habluetooth/models.py
There were a few attribute lookups can could be `cdef`s
This one is tiny. Only ~3% on test_inject_100_different_manufacturer_data
=> feat: improve performance of on demand AdvertisementData construction

src/habluetooth/manager.pxd, src/habluetooth/manager.py, tests/test_manager.py
Also adds a warning if the subclass does not implement `self._discovery_service_info`
=> feat: improve performance of dispatching discovery info to subclasses

src/habluetooth/__init__.py, src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, tests/test_base_scanner.py
This API is currently unstable and may be removed in the future without incrementing the major version number.
Do not use it yet
=> feat: add _async_on_raw_advertisement

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, tests/test_base_scanner.py, tests/test_benchmark_base_scanner.py
This API remains unstable and may be removed at any time
=> feat: rename _async_on_raw_advertisement to _async_on_raw_advertisements

src/habluetooth/__init__.py, src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, tests/test_base_scanner.py, tests/test_benchmark_base_scanner.py
This did not result in a useful performance improvement
=> fix: revert adding _async_on_advertisements

src/habluetooth/base_scanner.py
Its ~4% faster an gets rid of the ignores
=> feat: optimize previous local name matching

src/habluetooth/manager.pxd, src/habluetooth/manager.py
There was some ref counting to be avoided
=> feat: improve performance of _prefer_previous_adv_from_different_source

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py
This is only ~1% faster, but its slightly less code that wasn't reusable.
=> feat: improve performance of _async_on_advertisement

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, tests/test_base_scanner.py
https://github.com/home-assistant/core/issues/143769#issuecomment-2833594159
=> feat: add new _async_on_raw_advertisement base scanner API

src/habluetooth/base_scanner.pxd, src/habluetooth/base_scanner.py, src/habluetooth/models.pxd, src/habluetooth/models.py, src/habluetooth/scanner.py, tests/test_models.py
see https://github.com/home-assistant/core/issues/143769#issuecomment-2833594159
=> feat: add raw field to BluetoothServiceInfoBleak

src/habluetooth/__init__.py, src/habluetooth/base_scanner.py, src/habluetooth/storage.py, tests/test_storage.py
https://github.com/home-assistant/core/issues/143769#issuecomment-2833594159
=> feat: migrate storage code from bluetooth_adapters

src/habluetooth/base_scanner.py, src/habluetooth/storage.py, tests/test_base_scanner.py
https://github.com/home-assistant/core/issues/143769#issuecomment-2833594159
=> feat: save the raw data in storage

poetry.lock, pyproject.toml, src/habluetooth/manager.py, src/habluetooth/scanner.py, src/habluetooth/util.py, tests/test_manager.py, tests/test_scanner.py
Tell bluetooth-auto-recovery the adapter has gone silent so it knows to do the USB reset
=> feat: improve recovery when adapter has gone silent and needs a USB reset

src/habluetooth/manager.pxd, src/habluetooth/manager.py, src/habluetooth/wrappers.py, tests/test_manager.py, tests/test_wrappers.py
Improve sorting of the connections so we try to avoid connecting with the same adapter
=> feat: avoid thundering heard of connections

src/habluetooth/wrappers.py
fixes a regression introduced in https://github.com/Bluetooth-Devices/habluetooth/pull/219
=> fix: ensure connect works without debug logging
